name: docker

on:
  push:
    branches:
      - 'main'
    # paths:
    #   - 'Dockerfile'
    #   - 'poetry.lock'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      # - uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: pip install git+https://github.com/mishajw/remote
      - run: remote build ccs-2024-01-08
